name: alarm
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_time_picker_spinner: ^1.0.6+1
  uuid: ^3.0.4
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.14.0+3
  shared_preferences: ^2.0.5
  freezed_annotation: ^0.14.1
  android_alarm_manager: ^2.0.0
  flutter_ringtone_player: ^3.0.0
  receive_sharing_intent: ^1.4.5
  android_intent: ^2.0.0
  
  cupertino_icons: ^0.1.3

dependency_override:
  analyzer: "0.39.14"

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  build_runner: ^2.0.1
  freezed: ^0.14.1+3
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icons.png"

flutter:
  uses-material-design: true
