name: alarm
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+2

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  flutter_time_picker_spinner: ^1.0.6+1
  uuid: ^2.2.2
  flutter_hooks: ^0.14.0
  hooks_riverpod: ^0.11.0
  shared_preferences: ^0.5.12
  freezed_annotation:
  android_alarm_manager: ^0.4.5+20
  flutter_ringtone_player: ^2.0.0
  receive_sharing_intent: ^1.4.2
  android_intent: ^0.3.7+7
  
  cupertino_icons: ^0.1.3

dependency_override:
  analyzer: "0.39.14"

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  build_runner:
  freezed:
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icons.png"

flutter:
  uses-material-design: true
